version: "3.7"

services:
  db_book:
    image: postgres:11
    container_name: book_postgres_database
    restart: always
    ports:
      - "5432:5432"
    volumes:
      - postgres_volume:/var/lib/postgresql/data
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=database_db

  web_book:
    build: .
    container_name: web_book
    command: bash -c "alembic upgrade head && uvicorn main:app --host 0.0.0.0 --port 8000 --reload"
    volumes:
      - static:/code/static
      - .:/code
    ports:
      - "8000:8000"
    depends_on:
      - db_book

  pgadmin:
    container_name: book_postgres_admin
    image: dpage/pgadmin4
    environment:
      - PGADMIN_DEFAULT_EMAIL=pgadmin4@pgadmin.org
      - PGADMIN_DEFAULT_PASSWORD=admin
    ports:
      - "127.0.0.1:5050:80"
    depends_on:
      - db_book
  
  nginx:
    build:
      context: ./nginx
      dockerfile: Dockerfile.nginx
    container_name: nginx
    volumes:
      - static:/code/static
    ports:
      - "80:80"
    depends_on:
      - web_book

volumes:
  postgres_volume:
  static: