"""publisher removed

Revision ID: 3e9c1af424d6
Revises: 89e5b1fd949e
Create Date: 2021-06-09 16:01:10.402367

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '3e9c1af424d6'
down_revision = '89e5b1fd949e'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'publisher')
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publisher', sa.VARCHAR(length=50), autoincrement=False, nullable=False))
    # ### end Alembic commands ###
