"""publisher

Revision ID: 89e5b1fd949e
Revises: ab36bd62f42f
Create Date: 2021-06-09 15:56:41.419096

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '89e5b1fd949e'
down_revision = 'ab36bd62f42f'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('books', sa.Column('publisher', sa.String(length=50), nullable=False))
    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('books', 'publisher')
    # ### end Alembic commands ###
